def show_menu():
    print("\n" + "="*50)
    print("🏦 Welcome to Harshitha Bank")
    print("="*50)
    print("1️⃣  View Account Info")
    print("2️⃣  Transfer Fund")
    print("3️⃣  Change MPIN")
    print("4️⃣  Register Credit Card")
    print("5️⃣  View Transaction History")
    print("6️⃣  Logout")
    print("="*50)